### PR TITLE
Fix AreaShop integration for regions using capital characters in their name

### PR DESCRIPTION
**Pull request by NLthijs48**
This change fixes the AreaShop integration for regions that got added to AreaShop using capital characters (because that looks better on signs and in chat). Previously the id of a WorldGuard region, which is always lowercase, got compared to the, possibly not lowercase, name of the AreaShop region.

I also changed the AuthMe dependency to a local jar, since the Maven repository is down. And I changed the AreaShop dependency to use my Maven repository instead of a local jar.

PS: I'm the author of AreaShop and found out about this bug because of @tomtehtom.

### CODE REVIEW

**Comment by EpicEricEE** [comment]
Thank you :+1:

**Comment by EpicEricEE** [comment]
The build is failing now because maven can't access your pom file.

**Comment by NLthijs48** [comment]
Thanks for merging!

I made a mistake, the repository url should be http://maven.wiefferink.me

If you change that the build should work again :)

**Comment by EpicEricEE** [comment]
Alright, works now, thanks.

**Pull request merged**
