### PR TITLE
Added 1.16.4 Compatibility

### PR DESCRIPTION
**Pull request by white-sdev**
This might have bugs due to inability to test it thoroughly.
- Fixed some Exception Handling (Throwing exceptions in those sections instead of eating them)
- Removed a broken dependency and added local installation for the same.
- Added logs for the problematic sections
- Fixed and tested compatibility for 1.16.4 Spigot version.

### CODE REVIEW

**Review by StronglyHoldTV — APPROVED** [review]
Great code

**Comment by mechcalvin** [comment]
java newbie, how can i build jar file from this pull request?

**Comment by StronglyHoldTV** [comment]
> java newbie, how can i build jar file from this pull request?

You can simply download it from https://github.com/white-sdev/ShopChest/releases

**Comment by 42Atomys** [comment]
hi @white-sdev , I see your PR too late, nice adds I just give my feedback to merge our PR in yours

Two points : 
- The broken dependency can fixed with only change the repo to new official ( Link to my PR: https://github.com/EpicEricEE/ShopChest/pull/351 )

- Just in case : don't push development environnement settings to an open source repo. Use a gitignore in your local setup and dont push it or gitingore globally. Its principally to prevent a garbage of multitools file

**Comment by EpicEricEE** [comment]
I merged the other PR because there was a little too much going on here. Thanks nevertheless :)

**Pull request closed without merging**
