### PR TITLE
Implemented economy log cleanup

### LINKED ISSUE #154: Purge database
Hi,

I use the SQLite database, but it seems to be indefinitely growing (currently bigger than 100mb). It would be great if you could clear old data at server start or stop.

Thanks!

### PR DESCRIPTION
**Pull request by sigmaroot**
Fixes #154

### CODE REVIEW

**Comment by MineTheCube** [comment]
You should delete old `player_logout` entries as well.

And I think it would be more logic to put this code:
```java
// Clean up economy log
if (plugin.getShopChestConfig().cleanup_ecomomy_log) {
    cleanUpEconomy(true);
}
```

Before this one:
```java
PreparedStatement ps = connection.prepareStatement("SELECT * FROM shops");
ResultSet rs2 = ps.executeQuery();
```

**Comment by sigmaroot** [comment]
Why to delete `player_logout` as well? It does only store the last logout timestamp (once per player). Is this too much space using?

Moving up the clean up call could be more rational before initializing all shops if you have a huge shop amount (what takes a lot of time to initialize) but since it is called async you have no influence when it will be run. If moving up, this should be called **cleanUpEconomy(false);** to run it sync before initializing all shops.

Do you have any reasons of moving up it and calling it sync that I don't see at this point? If so I will change it this evening.

**Comment by MineTheCube** [comment]
If `player_logout` is only used with `shop_logs` for calculating what has been sold when player was offline, then this is useless data. But **I didn't check** if it is currently used for other features.
And space taken highly depends on server popularity, but it can grow by 10-100'000 entries every year.

Concerning cleanUpEconomy part, there is 2 things:
- Since you are already in an async thread, it is a bit pointless to run it in another thread.
- Currently the statement `if (cleanup_ecomomy_log) { cleanUpEconomy(true) }` splits the code of `Count entries in table "shops"`.
So I think it should be:
```java
// Clean up economy log
if (plugin.getShopChestConfig().cleanup_ecomomy_log) {
    cleanUpEconomy(false);
}

// Count entries in table "shops"
PreparedStatement ps = connection.prepareStatement("SELECT * FROM shops");
ResultSet rs2 = ps.executeQuery();

int count = 0;
while (rs2.next()) {
    if (rs2.getString("vendor") != null) count++;
}
plugin.debug("Initialized database with " + count + " entries");
```

**Comment by sigmaroot** [comment]
Yes, it is only used for `getLastLogout()` which is called only to notify the player on login. Because of this fact it is save to clear out too. I'm going to add it within the next few hours when I'm home.

True story, depending on @EpicEricEE coding style I didn't realize the counter part. I'm going to move it up.

**Comment by sigmaroot** [comment]
Done :)

**Comment by MineTheCube** [comment]
This sounds great, I'll test it live tomorrow!

**Comment by MineTheCube** [comment]
It seems that no messages are sent now, even if the player is offline just 1 hour or less, he doesn't get notified of what he sold.

**Comment by sigmaroot** [comment]
Sorry, I cannot confirm this. On my server, im running this update since a 2 weeks and I'm cleaning out everything that is older than 30 days and it is running fine. I'm getting the notification on login.

Did you try to regenerate your config.yml?
Remember, **enable-economy-log** must be set to **true**!

**Comment by sigmaroot** [comment]
I've tested this on:

`[Server] INFO This server is running Paper version git-Paper-1234 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

With the following config options:

```
# Set whether buys and sells should be logged in the database.
enable-economy-log: true

# Set whether the economy-log should be cleaned up on server start.
cleanup-ecomomy-log: true

# Sets the time limit for cleaning up the economy log in days.
# All log entries older than this will be deleted on server start.
cleanup-ecomomy-log-days: 1
```
**Important:** Only one day to test it, it is not recommented to clean out entries that are older than just one day!

I just logged out, someone buyed something and I logged back in after a few minutes.

Result: https://imgur.com/a/b9kO5

Maybe you have some miss-configurations. Check all the three values. If **enable-economy-log** is disabled, no log entries are saved and therefore no sales can be calculated. If you forget to set **cleanup-ecomomy-log-days** to an acceptable amount of days, maybe your complete economy log got cleared out (but this cannot be the case because sales must be logged correctly when not restarting (as you said, just logging out for some minutes)).

Next is: What version did you use before the update to the new version? Remember, you're running an development build, this is mostly more developed (and maybe buggy) than the official releases.

Next is: When you used a older version before, you might have to check that your files are **all** up to date (config.yml, language files, hologram-format.yml, ...).

Next is: Are there errors in the console? When logging in, or buying, selling, ...?

Next is: Enable debug log and look step for step what's happening.

Hope this helps!

**Pull request merged**
