### PR TITLE
Added purge() method

### PR DESCRIPTION
**Pull request by v3Monsta**
I haven't tested this but it should work... However, maybe you (Eric) can decide where a purge should be?

### CODE REVIEW

**Comment by EpicEricEE** [comment]
I'm not that familiar with SQL stuff but doesn't ``TRUNCATE TABLE ...`` and ``DELETE FROM ...`` delete all contents? Why would I need that?

**Comment by v3Monsta** [comment]
This was mainly a response to a request from [this](https://github.com/EpicEricEE/ShopChest/issues/132) issue.

**Comment by EpicEricEE** [comment]
Yes, but that does not mean that I should delete all data. 😕

**Comment by v3Monsta** [comment]
Okay, so maybe a time stamp could be added to the shops table so we know when it's been created, then have a config option to delete data after a certain amount of time?

**Comment by EpicEricEE** [comment]
What kind of data do you think should be deleted after a certain time span?
Shops should not be deleted, and removed shops are deleted from the database right after the removal.
Economy log should be deleted manually, but I'll add an option to disable it.
Logout times may be deleted after a long time, so that the revenue is still shown when joining after a long break, it could however be improved by only logging players that have shops.

**Comment by v3Monsta** [comment]
In that case perhaps there is no place for this method in the plugin. I wrote it just so there was an easy way to delete all data rather than having to manually delete the shops.db file or log into MySQL to do it.

**Comment by EpicEricEE** [comment]
Well, I don't see a need for that. If the server owner, for any reason, wants to delete all data, he should be capable of doing that manually.

**Pull request closed without merging**
